on:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Setup R dep
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: any::knitr
            any::rmarkdown

      - name: Create gh-pages branch if needed
        run: |
          if ! git ls-remote --heads origin gh-pages | grep -q refs/heads/gh-pages; then
            git checkout --orphan gh-pages
            git reset --hard
            git commit --allow-empty -m "Initialize gh-pages branch"
            git push origin gh-pages
            git checkout main
          fi

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: my_journey_with_vebisehr_reports.qmd
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
